// GENERATED by scripts/sync-server.mjs from src/sim/ — do not edit here.
/* End-of-game analysis: why the winner won (Key Success Factors). Rule-based on the game's own numbers,
   no AI (owner choice 9 Oct 2026; LLM narratives stay in P3). Pure: returns ids and numbers only,
   the UI turns them into text (src/ui/components/AnalysisPanel.jsx, i18n "ana").
   Every hotel in the market is the benchmark ("market average"), bots included.
   Thresholds below are game-design choices [ข้อเสนอ]. */
import { finalScores, seasonMult, SCORE_W } from './core.js';

const mean = a => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : 0);
const sd = a => { const m = mean(a); return Math.sqrt(mean(a.map(x => (x - m) ** 2))); };
function corr(a, b) {
  const ma = mean(a), mb = mean(b);
  let n = 0, da = 0, db = 0;
  a.forEach((x, i) => { n += (x - ma) * (b[i] - mb); da += (x - ma) ** 2; db += (b[i] - mb) ** 2; });
  return da && db ? n / Math.sqrt(da * db) : 0;
}
const avgPrice = p => (p.wd * 5 + p.we * 2) / 7;

/* fmt: how the UI prints the number. dir: +1 higher is better, -1 lower is better. */
export const FACTORS = [
  { id: 'rgi', fmt: 'idx', dir: 1 },            // RevPAR index vs the rest of the market
  { id: 'ari', fmt: 'idx', dir: 1 },            // ADR index (price power)
  { id: 'mpi', fmt: 'idx', dir: 1 },            // occupancy index (market share of room-nights)
  { id: 'season', fmt: 'corr', dir: 1 },        // price follows the season (correlation)
  { id: 'weekend', fmt: 'pct', dir: 1 },        // weekend price premium
  { id: 'service', fmt: 'num', dir: 1 },        // service quality minus guest expectation
  { id: 'staffing', fmt: 'pct', dir: 1 },       // staffing adequacy
  { id: 'teamSat', fmt: 'num', dir: 1 },        // staff satisfaction
  { id: 'stars', fmt: 'stars', dir: 1 },        // final review rating
  { id: 'mkRoi', fmt: 'ratio', dir: 1 },        // revenue per baht of marketing
  { id: 'awareness', fmt: 'pct', dir: 1 },      // average awareness
  { id: 'costRoom', fmt: 'baht', dir: -1 },     // operating cost per occupied room-night
  { id: 'growth', fmt: 'rooms', dir: 1 },       // rooms at the end (8 or 16)
  { id: 'fnb', fmt: 'pct', dir: 1 },            // F&B share of revenue
  { id: 'crises', fmt: 'count', dir: -1 },      // internal crises + fake reviews caught
];
const MIN_EDGE = 0.25;   // a factor counts as a "key" only if the winner is at least 0.25 SD better than the market [ข้อเสนอ]

function metrics(g) {
  const weeks = g.hotels[0].history.length;
  const season = Array.from({ length: weeks }, (_, w) => seasonMult(g, w));
  const others = (h, w, f) => mean(g.hotels.filter(x => x !== h).map(x => f(x.history[w])).filter(Number.isFinite));
  const out = {};
  g.hotels.forEach(h => {
    const H = h.history;
    const idx = (f, okW = () => true) => mean(H.map((r, w) => {
      if (!okW(r, w)) return NaN;
      const o = others(h, w, f);
      return o ? f(r) / o * 100 : NaN;
    }).filter(Number.isFinite));
    const sold = H.reduce((a, r) => a + r.sold, 0);
    const rev = H.reduce((a, r) => a + r.revenue + (r.fnb?.revenue || 0), 0);
    const mk = H.reduce((a, r) => a + (r.costs.marketing || 0), 0);
    const opCost = H.reduce((a, r) => a + r.costTotal - (r.costs.invest || 0), 0);
    const active = H.filter(r => r.sold > 0);
    out[h.id] = {
      rgi: idx(r => r.revpar),
      ari: idx(r => r.adr, r => r.sold > 0),
      mpi: idx(r => r.occ),
      season: corr(H.map(r => avgPrice(r.price)), season),
      weekend: mean(H.map(r => r.price.we / r.price.wd - 1)),
      service: active.length ? mean(active.map(r => r.Q - r.E)) : null,
      staffing: mean(H.map(r => Math.min(r.adequacy || 0, 1.2))),
      teamSat: mean(H.map(r => r.teamSat || 0)),
      stars: h.R,
      mkRoi: mk > 0 ? rev / mk : null,
      awareness: mean(H.map(r => r.awAvg)),
      costRoom: sold ? opCost / sold : null,
      growth: h.rooms,
      fnb: rev ? H.reduce((a, r) => a + (r.fnb?.revenue || 0), 0) / rev : 0,
      crises: H.reduce((a, r) => a + (r.crises?.length || 0), 0) + (h.fakeCaught || 0),
    };
  });
  return out;
}

/* Weekly decisions + results of one hotel (shown to everyone at the end, owner decision 9 Oct 2026). */
function weekly(g, h) {
  return h.history.map((r, w) => {
    const o = mean(g.hotels.filter(x => x !== h).map(x => x.history[w].revpar));
    return {
      week: w + 1, pwd: r.price.wd, pwe: r.price.we, staff: r.staffN, roles: r.roles, bonus: r.costs.bonus,
      marketing: r.costs.marketing, inf: r.inf, fake: r.fake, rooms: r.rooms,
      occ: r.occ, adr: r.adr, revpar: r.revpar, rgi: o ? r.revpar / o * 100 : 0, R: r.R, profit: r.profit,
    };
  });
}

/* Key factors of one hotel: where it beat the market by the most standard deviations. */
function keysOf(id, m) {
  return FACTORS.map(f => {
    const vals = Object.values(m).map(x => x[f.id]).filter(v => v !== null && Number.isFinite(v));
    const v = m[id][f.id], s = sd(vals);
    return { id: f.id, edge: v === null || !Number.isFinite(v) || !s ? 0 : f.dir * (v - mean(vals)) / s };
  }).filter(k => k.edge >= MIN_EDGE).sort((a, b) => b.edge - a.edge).slice(0, 3).map(k => k.id);
}

export function analyseGame(g) {
  const fs = finalScores(g);
  const m = metrics(g);
  const winner = fs[0];
  const bestPlayer = fs.find(f => g.hotels.find(h => h.id === f.id).isPlayer);
  const avgPart = k => mean(fs.map(f => f[k]));
  const parts = Object.fromEntries(['fin', 'rep', 'staff'].map(k => [k, { winner: winner[k], avg: avgPart(k), w: SCORE_W[k] }]));
  const mainPart = Object.entries(parts).sort((a, b) => b[1].w * (b[1].winner - b[1].avg) - a[1].w * (a[1].winner - a[1].avg))[0][0];
  const market = Object.fromEntries(FACTORS.map(f => {
    const vals = Object.values(m).map(x => x[f.id]).filter(v => v !== null && Number.isFinite(v));
    return [f.id, vals.length ? mean(vals) : null];
  }));
  const hotelOf = id => g.hotels.find(h => h.id === id);
  const res = {
    winner: winner.id, bestPlayer: bestPlayer?.id || null, parts, mainPart,
    keys: { [winner.id]: keysOf(winner.id, m) },
    values: m, market,
    weekly: { [winner.id]: weekly(g, hotelOf(winner.id)) },
  };
  if (bestPlayer && bestPlayer.id !== winner.id) {
    res.keys[bestPlayer.id] = keysOf(bestPlayer.id, m);
    res.weekly[bestPlayer.id] = weekly(g, hotelOf(bestPlayer.id));
  }
  return res;
}

/* Same analysis with one hotel renamed (classroom: the student's own hotel is 'you'). */
export function renameAnalysis(a, from, to) {
  const r = x => (x === from ? to : x);
  const re = o => Object.fromEntries(Object.entries(o).map(([k, v]) => [r(k), v]));
  return { ...a, winner: r(a.winner), bestPlayer: r(a.bestPlayer), keys: re(a.keys), values: re(a.values), weekly: re(a.weekly) };
}
