// GENERATED by scripts/sync-server.mjs from src/sim/ — do not edit here.
/* Hotel Pixel Simulation - economy core (from prototype P0 v0.3).
   Pure + deterministic: same seed -> same game. No DOM access.
   No display text: names and descriptions live in src/i18n/<lang>.json under "data", keyed by id. */
/* Seeded RNG. rng.state() exposes the internal counter so a saved game can resume with mulberry32(state)
   and get exactly the same next numbers (see src/sim/save.js). */
function mulberry32(a){const rng=function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};rng.state=()=>a|0;return rng;}
function hashSeed(str){let h=1779033703^str.length;for(let i=0;i<str.length;i++){h=Math.imul(h^str.charCodeAt(i),3432918353);h=h<<13|h>>>19;}return h>>>0;}
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const r100=x=>Math.round(x/100)*100, r10=x=>Math.round(x/10)*10;
const ROOMS=8,NIGHTS={wd:5,we:2},WEEKS=12;
const SEGMENTS=[
 {id:'bp',wtp:450,bp:3.0,wdShare:.70,w:{app:.15,serv:.45,exp:.25,prof:.15},fb:1.3},
 {id:'fam',wtp:900,bp:2.2,wdShare:.35,w:{app:.2,serv:.4,exp:.25,prof:.15},fb:0.3},
 {id:'cpl',wtp:1300,bp:1.6,wdShare:.45,w:{app:.35,serv:.35,exp:.15,prof:.15},fb:1.0},
 {id:'biz',wtp:1700,bp:1.2,wdShare:.9,w:{app:.2,serv:.2,exp:.25,prof:.35},fb:0.8}
];
const MAPS={
 city:{cities:['bkk','kkn']},
 sea:{cities:['hkt','pty']},
 town:{cities:['pbi','rbr','rng']},
 mountain:{cities:['cnx','pnb']}
};
const CITIES={
 bkk:{map:'city',lat:13.75,lon:100.50,flood:true,quake:false,coast:false,andaman:false,haze:true,mice:2,protest:2,demand:{bp:90,fam:35,cpl:50,biz:110},foreign:.55,monthly:[1.12,1.08,1.0,1.02,0.92,0.88,0.9,0.92,0.86,0.94,1.08,1.18]},
 kkn:{map:'city',lat:16.43,lon:102.83,flood:true,quake:false,coast:false,andaman:false,haze:true,mice:2,protest:.5,demand:{bp:30,fam:70,cpl:40,biz:125},foreign:.1,monthly:[1.05,1.0,0.95,1.1,0.9,0.92,0.95,0.95,0.92,1.0,1.08,1.15]},
 hkt:{map:'sea',lat:7.88,lon:98.39,flood:false,quake:false,coast:true,andaman:true,haze:false,mice:1,protest:.3,demand:{bp:140,fam:45,cpl:150,biz:12},foreign:.8,monthly:[1.28,1.3,1.2,1.08,0.8,0.68,0.75,0.75,0.65,0.78,1.05,1.3]},
 pty:{map:'sea',lat:12.93,lon:100.88,flood:false,quake:false,coast:true,andaman:false,haze:false,mice:2,protest:.3,demand:{bp:110,fam:70,cpl:120,biz:25},foreign:.6,monthly:[1.18,1.15,1.05,1.12,0.9,0.82,0.85,0.88,0.78,0.92,1.08,1.25]},
 pbi:{map:'town',lat:13.11,lon:99.94,flood:true,quake:false,coast:true,andaman:false,haze:false,mice:0,protest:.3,demand:{bp:25,fam:130,cpl:60,biz:35},foreign:.08,monthly:[1.1,1.0,1.08,1.15,1.02,0.85,0.88,0.9,0.8,1.0,1.0,1.18]},
 rbr:{map:'town',lat:13.54,lon:99.81,flood:true,quake:false,coast:false,andaman:false,haze:false,mice:0,protest:.3,demand:{bp:25,fam:110,cpl:55,biz:45},foreign:.06,monthly:[1.12,1.02,0.98,1.05,0.92,0.85,0.9,0.9,0.85,0.98,1.1,1.25]},
 rng:{map:'town',lat:9.96,lon:98.64,flood:true,quake:false,coast:true,andaman:true,haze:false,mice:0,protest:.2,demand:{bp:50,fam:70,cpl:70,biz:25},foreign:.22,monthly:[1.2,1.25,1.2,1.12,0.85,0.72,0.65,0.72,0.75,0.8,1.0,1.2]},
 cnx:{map:'mountain',lat:18.79,lon:98.98,flood:true,quake:true,coast:false,andaman:false,haze:true,mice:1,protest:.3,demand:{bp:110,fam:70,cpl:110,biz:25},foreign:.45,monthly:[1.35,1.15,0.9,0.95,0.78,0.72,0.82,0.85,0.8,0.95,1.25,1.45]},
 pnb:{map:'mountain',lat:16.42,lon:101.16,flood:true,quake:false,coast:false,andaman:false,haze:true,mice:0,protest:.2,demand:{bp:20,fam:125,cpl:115,biz:15},foreign:.05,monthly:[1.45,1.05,0.8,0.9,0.7,0.65,0.75,0.75,0.75,0.95,1.35,1.6]}
};
/* ---------- calendar ---------- */
function weekStart(g,w){return new Date(Date.UTC(2027,g.startMonth,1+7*w));}
function weekInfo(g,w){const s=weekStart(g,w),e=new Date(s.getTime()+6*864e5),mid=new Date(s.getTime()+3*864e5);
  return {start:s,end:e,month:mid.getUTCMonth(),day:mid.getUTCDate()};}
function tmdSeason(m,d){ // NSO/TMD: summer mid-Feb–mid-May, rainy mid-May–mid-Oct, winter mid-Oct–mid-Feb
  if((m===1&&d>=15)||m===2||m===3||(m===4&&d<15))return 'summer';
  if((m===4&&d>=15)||(m>=5&&m<=8)||(m===9&&d<15))return 'rainy';return 'winter';}
function monthIdx(city,m,d){const a=CITIES[city].monthly;const f=(d-15)/30;if(f>=0)return a[m]*(1-f)+a[(m+1)%12]*f;return a[m]*(1+f)+a[(m+11)%12]*(-f);}
function seasonMult(g,w){const wi=weekInfo(g,w);return monthIdx(g.city,wi.month,wi.day);}
function seasonLabel(x){return x>=1.1?'high':x<=0.85?'low':'shoulder';}
/* ---------- scheduled events ---------- */
const NATIONAL=[
 {id:'songkran',m:3,d:13,mult:{bp:1.3,fam:1.6,cpl:1.3,biz:.6}},
 {id:'loykrathong',m:10,d:15,mult:{bp:1.15,fam:1.2,cpl:1.45,biz:.9}},
 {id:'newyear',m:11,d:31,mult:{bp:1.3,fam:1.45,cpl:1.4,biz:.5}},
 {id:'cny',m:1,d:5,mult:{fam:1.2,cpl:1.1},foreign:1.2},
 {id:'vegfest',m:9,d:1,city:'hkt',mult:{fam:1.3,bp:1.15},foreign:1.1}
];
const SEEDED=[
 {id:'concert',mult:{bp:1.5,cpl:1.4}},
 {id:'conference',mult:{biz:1.9},foreign:1.1,mice:true},
 {id:'marathon',mult:{bp:1.3,fam:1.25,cpl:1.15}},
 {id:'tradefair',mult:{biz:1.5,fam:1.1},mice:true},
 {id:'sport',mult:{bp:1.4,cpl:1.2,biz:1.15},foreign:1.2}
];
const CANCEL_P=.12;
/* ---------- shock library ---------- */
const SHOCKS=[
 {id:'quake',cat:'macro',sev:'cat',where:c=>c.quake,w:1,dur:[2,3],eff:{all:.55,foreign:.8}},
 {id:'tsunami',cat:'macro',sev:'cat',where:c=>c.andaman,w:.6,dur:[4,5],eff:{all:.35}},
 {id:'flood',cat:'macro',sev:'major',where:c=>c.flood,months:[6,7,8,9,10],w:2,dur:[2,3],eff:{all:.55,cost:1.25}},
 {id:'storm',cat:'macro',sev:'minor',where:()=>true,months:[4,5,6,7,8,9,10],w:3,dur:[1,1],eff:{all:.7},repeat:true},
 {id:'pandemic',cat:'macro',sev:'cat',where:()=>true,w:.5,dur:[6,8],eff:{foreign:.15,domestic:.55}},
 {id:'haze',cat:'macro',sev:'minor',where:c=>c.haze,months:[0,1,2,3],w:2,dur:[2,2],eff:{all:.85,foreign:.85}},
 {id:'recession',cat:'macro',sev:'major',where:()=>true,w:1.5,dur:[4,5],eff:{all:.85,wtp:.88}},
 {id:'fxstrong',cat:'macro',sev:'minor',where:()=>true,w:1.5,dur:[3,3],eff:{foreign:.85}},
 {id:'fxweak',cat:'macro',sev:'minor',where:()=>true,w:1.5,dur:[3,3],eff:{foreign:1.15},positive:true},
 {id:'energy',cat:'macro',sev:'minor',where:()=>true,w:2,dur:[3,3],eff:{cost:1.3}},
 {id:'protest',cat:'political',sev:'major',where:()=>true,wf:c=>c.protest,w:1,dur:[2,3],eff:{foreign:.6,biz:.75,domestic:.9}},
 {id:'politics',cat:'political',sev:'major',where:()=>true,w:.6,dur:[4,4],eff:{foreign:.65,biz:.8}},
 {id:'terror',cat:'political',sev:'cat',where:()=>true,w:.4,dur:[3,4],eff:{foreign:.5,domestic:.75}},
 {id:'advisory',cat:'political',sev:'minor',where:()=>true,w:1.5,dur:[3,3],eff:{foreign:.7}},
 {id:'newcomp',cat:'industry',sev:'major',where:()=>true,w:1.5,perm:true,eff:{A0:1.18}},
 {id:'airbnb',cat:'industry',sev:'minor',where:()=>true,w:1.5,perm:true,eff:{A0:1.1}},
 {id:'labour',cat:'industry',sev:'minor',where:()=>true,w:2,dur:[1,1],eff:{staffHit:10},repeat:true},
 {id:'viral',cat:'industry',sev:'minor',where:()=>true,w:2,dur:[2,2],eff:{foreign:1.3},positive:true},
 {id:'flight',cat:'industry',sev:'minor',where:()=>true,w:1.2,dur:[4,4],eff:{foreign:1.25},positive:true},
 {id:'stimulus',cat:'industry',sev:'minor',where:()=>true,w:1.5,dur:[2,2],eff:{domestic:1.25},positive:true},
 {id:'film',cat:'industry',sev:'minor',where:()=>true,w:1,dur:[3,3],eff:{cpl:1.3,bp:1.2},positive:true}
];
const INTERNAL=[
 {id:'pr',variants:4},
 {id:'overbook'},
 {id:'repair'},
 {id:'gouging'}
];
const CHAOS={low:{p:.15,max:1,scale:.7,sevW:{minor:1,major:.25,cat:0}},mid:{p:.3,max:1,scale:1,sevW:{minor:1,major:.7,cat:.12}},high:{p:.4,max:2,scale:1.25,sevW:{minor:1,major:1,cat:.45}}};
const CHANNELS={
 billboard:{decay:.8,eff:{bp:.1,fam:.35,cpl:.2,biz:.25}},
 online:{decay:.5,eff:{bp:.6,fam:.4,cpl:.55,biz:.4}},
 influencer:{decay:.65,eff:{bp:.6,fam:.25,cpl:.8,biz:.1}}
};
const INFLUENCER={none:{cost:0},micro:{cost:3000,cred:[.5,1.1]},macro:{cost:9000,cred:[.7,1.4]}};
const OTA_BOOST={bp:.45,fam:.2,cpl:.35,biz:.3},OTA_COMMISSION=.15;
const BASE_AW=.12,AW_K=.25,A0_BASE=.9;
/* Whole-class market (owner decision 9 Oct 2026): city demand and the 'stay nowhere' option both scale with
   hotels/MARKET_UNIT, so n hotels share a market like n/4 copies of the 4-hotel game. 4 hotels => x1 (single player unchanged). */
const MARKET_UNIT=4;
const marketScale=g=>g.hotels.length/MARKET_UNIT;
const COST={fixed:12000,perRoomNight:200,fake:1500,fine:5000,interest:.01,repair:8000,overbook:3000};
const START_CASH=60000;
const SCORE_W={fin:.5,rep:.35,staff:.15};
/* Staff positions (P1 step 5) [design values]. Each position serves every guest, so a person can
   handle `cap` room-nights a week before satisfaction drops; a team split evenly between front office
   and housekeeping behaves exactly like the old single team. `q` = share of service quality. */
const MAX_STAFF=4; // T0 limit; see TIERS
/* Growth path (P1 step 6) [design values]. Thai law: more than 8 rooms / 30 guests needs a hotel licence;
   Type 1 = rooms only, Type 2 = rooms + restaurant (Ministerial Regulation B.E. 2551). Game time is compressed. */
const TIERS=[{rooms:8,maxStaff:4},{rooms:16,maxStaff:6},{rooms:16,maxStaff:8}];
// Owner approved set A (8 Oct 2026) after simulating 216 games per strategy; see docs/spec-summary.md.
const GROWTH={licenceCost:25000,licenceWeeks:2,buildCost:60000,buildWeeks:2,restCost:30000,restWeeks:2,
  fixedPerExtraRoom:600,restFixed:5000,
  sizePow:1}; // demand attraction ∝ (rooms/8)^sizePow: "fair share" follows room supply (STR); 8 rooms -> unchanged
const FNB={spend:{bp:120,fam:450,cpl:380,biz:300},capture:{bp:.25,fam:.6,cpl:.5,biz:.45},walkIn:50,walkInSpend:220,foodCost:.35,cap:150,qBoost:2};
const ROLES={fo:{q:.6,cap:30},hk:{q:.4,cap:30},fb:{q:0,cap:30}};
const HK_COVER=.7; // front office cleaning rooms when nobody is in housekeeping: 70% as good (owner approved 8 Oct 2026; tested .5 = too harsh)
const LOAD_HIT=.6; // satisfaction lost per room-night above cap (old rule: 1.2 per room-night above 15 per person)
const CAND_ROLES=['fo','fo','fo','hk','hk','hk','fb','fb'];
const LANG_RANGE={fo:[5,95],hk:[5,60],fb:[5,80]};
const NAMES=['ton','fon','bank','mind','nat','pla','jay','aom','beam','praew']; // display names: i18n data.staff
const ARCH={
 budget:{pf:.65,wef:1.1,staff:[{role:'fo',app:45,serv:55,exp:50,prof:40,lang:50},{role:'hk',app:40,serv:50,exp:45,prof:40,lang:45}],bonus:300,mk:{billboard:0,online:800},ota:true,inf:()=>'none'},
 luxury:{pf:1.45,wef:1.2,staff:[{role:'fo',app:88,serv:72,exp:70,prof:82,lang:80},{role:'fo',app:85,serv:70,exp:68,prof:80,lang:75},{role:'hk',app:80,serv:68,exp:72,prof:78,lang:70}],bonus:1500,mk:{billboard:1500,online:600},ota:true,inf:w=>w%4===0?'macro':'none'},
 marketing:{pf:1.0,wef:1.15,staff:[{role:'fo',app:68,serv:60,exp:56,prof:56,lang:65},{role:'hk',app:62,serv:58,exp:54,prof:54,lang:60}],bonus:300,mk:{billboard:300,online:2500},ota:true,inf:w=>w%2===0?'micro':'none'},
 service:{pf:1.15,wef:1.15,staff:[{role:'fo',app:62,serv:88,exp:78,prof:66,lang:62},{role:'hk',app:60,serv:85,exp:75,prof:64,lang:58},{role:'hk',app:58,serv:84,exp:72,prof:62,lang:55}],bonus:1500,mk:{billboard:600,online:400},ota:false,inf:()=>'none'}
};
const SKILL={low:{step:.04,noise:.08,wrong:.3,look:0,event:0},mid:{step:.06,noise:.04,wrong:.1,look:.5,event:.5},high:{step:.08,noise:.01,wrong:0,look:1,event:1}};
function salaryOf(s){return r100(1500+22*(s.app+s.serv+s.exp+s.prof)/4+6*s.lang);}
function makeCandidates(rng){const out=[];const names=NAMES.slice();
  for(let i=0;i<8;i++){const nm=names.splice(Math.floor(rng()*names.length),1)[0];const st=()=>Math.round(30+rng()*65);
    const role=CAND_ROLES[i],[lo,hi]=LANG_RANGE[role];const s={id:'c'+i,name:nm,role,app:st(),serv:st(),exp:st(),prof:st(),lang:Math.round(lo+rng()*(hi-lo)),sat:70,look:Math.floor(rng()*1e9)};s.salary=salaryOf(s);out.push(s);}
  return out;}
function refPrice(city){const c=CITIES[city];let n=0,d=0;SEGMENTS.forEach(s=>{n+=s.wtp*c.demand[s.id];d+=c.demand[s.id];});return n/d;}
function pickWeighted(rng,items,wf){let t=0;const ws=items.map(i=>{const w=Math.max(0,wf(i));t+=w;return w;});if(t<=0)return null;let r=rng()*t;for(let k=0;k<items.length;k++){r-=ws[k];if(r<=0)return items[k];}return items[items.length-1];}
function buildTimeline(g,rng){
  const c=CITIES[g.city],ch=CHAOS[g.chaos];const tl=[];for(let w=0;w<WEEKS;w++)tl.push({scheduled:[],shocks:[]});
  // national/city scheduled
  NATIONAL.forEach(e=>{if(e.city&&e.city!==g.city)return;for(let w=0;w<WEEKS;w++){const s=weekStart(g,w);for(let k=0;k<7;k++){const d=new Date(s.getTime()+k*864e5);if(d.getUTCMonth()===e.m&&d.getUTCDate()===e.d){tl[w].scheduled.push(Object.assign({kind:'national',cancelled:false},e));}}}});
  // seeded city events
  const n=2+(c.mice>=2?1:0);const freeWeeks=[];for(let w=1;w<WEEKS;w++)if(!tl[w].scheduled.length)freeWeeks.push(w);
  for(let i=0;i<n&&freeWeeks.length;i++){const w=freeWeeks.splice(Math.floor(rng()*freeWeeks.length),1)[0];
    const t=pickWeighted(rng,SEEDED,x=>x.mice?(.5+c.mice*.6):1);tl[w].scheduled.push(Object.assign({kind:'city',cancelled:rng()<CANCEL_P},t));}
  // shocks
  const used=new Set();const active={};const lastStart={};const COOLDOWN=4;
  for(let w=0;w<WEEKS;w++){
    const draws=[];for(let k=0;k<ch.max;k++)if(rng()<ch.p)draws.push(k);
    draws.forEach(()=>{const wi=weekInfo(g,w);
      const pool=SHOCKS.filter(s=>s.where(c)&&(!s.months||s.months.includes(wi.month))&&!active[s.id]&&(s.repeat?(lastStart[s.id]===undefined||w-lastStart[s.id]>=COOLDOWN):!used.has(s.id)));
      const s=pickWeighted(rng,pool,x=>x.w*(x.wf?x.wf(c):1)*ch.sevW[x.sev]);if(!s)return;
      used.add(s.id);lastStart[s.id]=w;const d=s.perm?WEEKS-w:(s.dur[0]+Math.floor(rng()*(s.dur[1]-s.dur[0]+1)));active[s.id]=w+d;
      for(let k=0;k<d&&w+k<WEEKS;k++)tl[w+k].shocks.push({ev:s,k,d,start:w,perm:!!s.perm});});
    Object.keys(active).forEach(id=>{if(active[id]<=w+1)delete active[id];});
  }
  return tl;
}
function newHotel(id,name,isPlayer){return {id,name,isPlayer,price:{wd:0,we:0},staff:[],bonus:0,mk:{billboard:0,online:0},inf:'none',ota:true,fake:false,
  rooms:8,tier:0,proj:{},restaurant:false,invest:0,stock:{billboard:0,online:0,influencer:0},R:3.5,N:8,cash:START_CASH,otaBan:0,profitCum:0,history:[],fakeCaught:0,closed:0,closedWeeks:0,crises:[]};}
/* Single player: opts.hotelName/ownerName -> player 'you' + 3 bots (unchanged since P1).
   Classroom (P2): opts.players=[{id,hotelName,ownerName}] + opts.bots (0-3) -> one market. Each player gets their own
   8 applicants from an RNG seeded by game seed + player id, so pools don't depend on join order or the main RNG. */
function newGame(opts){
  const rng=mulberry32(hashSeed(String(opts.seed)));const multi=Array.isArray(opts.players);
  const g={hotelName:opts.hotelName,seed:opts.seed,city:opts.city,startMonth:opts.startMonth,chaos:opts.chaos,allowFake:!!opts.allowFake,week:0,rng,news:[]};
  if(multi)g.multi=true;
  g.refP=refPrice(opts.city);g.candidates=multi?[]:makeCandidates(rng);g.timeline=buildTimeline(g,rng);
  const archKeys=Object.keys(ARCH);for(let i=archKeys.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[archKeys[i],archKeys[j]]=[archKeys[j],archKeys[i]];}
  const skills=['low','mid','high'];for(let i=2;i>0;i--){const j=Math.floor(rng()*(i+1));[skills[i],skills[j]]=[skills[j],skills[i]];}
  const startPlayer=(id,name,owner)=>{const p=newHotel(id,name||'',true);p.owner=String(owner||'').trim();p.price.wd=r10(g.refP);p.price.we=r10(g.refP*1.15);p.mk.online=1000;return p;};
  if(multi){g.hotels=opts.players.map(pl=>{const p=startPlayer(pl.id,pl.hotelName,pl.ownerName);p.candidates=makeCandidates(mulberry32(hashSeed(String(opts.seed)+'|'+pl.id)));return p;});}
  else g.hotels=[startPlayer('you',opts.hotelName,opts.ownerName)];
  const nBots=multi?clamp(Math.round(opts.bots||0),0,3):3;
  if(g.hotels.length+nBots<2)throw new Error('a market needs at least 2 hotels');
  for(let i=0;i<nBots;i++){const a=ARCH[archKeys[i]];const b=newHotel('bot'+i,'',false);b.arch=archKeys[i];b.skill=skills[i];
    const nz=1+(rng()-.5)*.1;b.price.wd=r10(g.refP*a.pf*nz);b.price.we=r10(b.price.wd*a.wef);
    b.staff=a.staff.map((s,k)=>Object.assign({id:b.id+'s'+k,name:'',sat:70},s,{salary:salaryOf(s)}));b.bonus=a.bonus;b.mk=Object.assign({},a.mk);b.ota=a.ota;g.hotels.push(b);}
  return g;}
function schedMultFor(e,seg){return (e.mult&&e.mult[seg.id])||1;}
function botDecide(g,b){
  const a=ARCH[b.arch],sk=SKILL[b.skill],rng=g.rng;const last=b.history[b.history.length-1];
  const sNext=seasonMult(g,g.week),sNow=g.week>0?seasonMult(g,g.week-1):1;
  const known=g.timeline[g.week].scheduled.length>0;
  ['wd','we'].forEach(p=>{let price=b.price[p];
    if(last){const occ=last.occP[p];let dir=0;if(occ>.88)dir=1;else if(occ<.55)dir=-1;if(dir!==0&&rng()<sk.wrong)dir=-dir;price*=1+dir*sk.step;}
    price*=1+sk.look*.35*(sNext-sNow);
    if(known)price*=1+.12*sk.event; if(g.week>0&&g.timeline[g.week-1].scheduled.length&&!known)price*=1-.1*sk.event;
    price*=1+(rng()*2-1)*sk.noise;b.price[p]=r10(clamp(price,g.refP*.4,g.refP*2.5));});
  b.inf=a.inf(g.week+1);}
function awareness(h,seg){let x=0;Object.keys(CHANNELS).forEach(c=>{x+=CHANNELS[c].eff[seg.id]*h.stock[c];});
  let aw=BASE_AW+(1-BASE_AW)*(1-Math.exp(-AW_K*x));let otaPart=0;
  if(h.ota&&h.otaBan===0){const tot=1-(1-aw)*(1-OTA_BOOST[seg.id]);otaPart=tot-aw;aw=tot;}return {aw,otaShare:aw>0?otaPart/aw:0};}
const avgOf=(a,f)=>a.reduce((x,s)=>x+f(s),0)/a.length;
const hkSkill=s=>.8*s.exp+.2*s.serv; // rooms ready and clean as promised (Reliability) + care
/* Service quality for one segment: 60% front office (guest contact, language) + 40% housekeeping. */
function teamQuality(h,seg,fs,sold){
  const fo=h.staff.filter(s=>s.role==='fo'),hk=h.staff.filter(s=>s.role==='hk');
  if(!fo.length)return {q:0,adequacy:0,lang:0,base:0,qFO:0,qHK:0,adFO:0,adHK:0};
  const wF=seg.w.app+seg.w.serv+seg.w.prof;
  const foBase=avgOf(fo,s=>(seg.w.app*s.app+seg.w.serv*s.serv+seg.w.prof*s.prof)/wF);
  const hkBase=hk.length?avgOf(hk,hkSkill):HK_COVER*avgOf(fo,hkSkill);
  const need=.5+sold/42; // people needed per position; both together = 1 + room-nights/21 as before
  const adFO=hk.length?Math.min(1,fo.length/need):Math.min(1,fo.length/(2*need));
  const adHK=hk.length?Math.min(1,hk.length/need):adFO;
  const satFO=avgOf(fo,s=>s.sat),satHK=hk.length?avgOf(hk,s=>s.sat):satFO;
  const qFO=foBase*(0.55+0.45*adFO)*(0.85+0.15*satFO/100),qHK=hkBase*(0.55+0.45*adHK)*(0.85+0.15*satHK/100);
  const lang=avgOf(fo,s=>s.lang);
  let q=ROLES.fo.q*qFO+ROLES.hk.q*qHK;const qF=q-Math.max(0,60-lang)*0.4;q=q*(1-fs)+qF*fs;
  return {q,adequacy:Math.min(adFO,adHK),lang,base:ROLES.fo.q*foBase+ROLES.hk.q*hkBase,qFO,qHK,adFO,adHK};}
function weekEffects(g,w){
  const tl=g.timeline[w],ch=CHAOS[g.chaos];const E={seg:{},foreign:1,domestic:1,cost:1,A0:1,staffHit:0,wtp:1,list:[]};
  SEGMENTS.forEach(s=>E.seg[s.id]=1);
  tl.scheduled.forEach(e=>{if(e.cancelled)return;SEGMENTS.forEach(s=>E.seg[s.id]*=schedMultFor(e,s));if(e.foreign)E.foreign*=e.foreign;});
  tl.shocks.forEach(sh=>{const inten=sh.perm?1:1-sh.k/sh.d;const sc=m=>1+(m-1)*ch.scale*inten;const f=sh.ev.eff;
    if(f.all)SEGMENTS.forEach(s=>E.seg[s.id]*=sc(f.all));SEGMENTS.forEach(s=>{if(f[s.id])E.seg[s.id]*=sc(f[s.id]);});
    if(f.foreign)E.foreign*=sc(f.foreign);if(f.domestic)E.domestic*=sc(f.domestic);if(f.cost)E.cost*=sc(f.cost);if(f.A0)E.A0*=f.A0;if(f.wtp)E.wtp*=sc(f.wtp);
    if(f.staffHit)E.staffHit+=f.staffHit*ch.scale*inten;});
  return E;}
/* Restaurant (Type 2): meals for staying guests (by segment) + walk-in diners; needs at least one F&B staff. */
function restaurantWeek(g,h,r,season,E,sold){
  const fb=h.staff.filter(s=>s.role==='fb');
  if(!h.restaurant||!fb.length){h.lastCovers=0;return {revenue:0,foodCost:0,covers:0,guests:0,walkIns:0,q:0};}
  const q=avgOf(fb,s=>.4*s.serv+.3*s.exp+.3*s.app);
  const qf=clamp(q/70,.5,1.2);
  let guestRev=0,guests=0;SEGMENTS.forEach(sg=>{const n=(r.seg[sg.id]||0)*FNB.capture[sg.id]*qf;guests+=n;guestRev+=n*FNB.spend[sg.id];});
  let aw=0;SEGMENTS.forEach(sg=>aw+=r.aw[sg.id]/4);
  const walkIns=FNB.walkIn*season*E.domestic*qf*(0.5+aw);
  const covers=guests+walkIns;const need=covers/FNB.cap;const ad=Math.min(1,fb.length/Math.max(.5,need));
  const revenue=(guestRev+walkIns*FNB.walkInSpend)*(0.7+0.3*ad);
  h.lastCovers=covers;
  return {revenue,foodCost:revenue*FNB.foodCost,covers,guests,walkIns,q};}
/* Weekly countdown of licence -> construction -> restaurant. */
function advanceProjects(h){const p=h.proj;
  if(p.licence){p.licence--;if(!p.licence){delete p.licence;h.tier=Math.max(h.tier,1);p.build=GROWTH.buildWeeks;h.invest+=GROWTH.buildCost;}}
  else if(p.build){p.build--;if(!p.build){delete p.build;h.rooms=TIERS[1].rooms;}}
  if(p.rest){p.rest--;if(!p.rest){delete p.rest;h.restaurant=true;h.tier=2;}}}
/* Player actions. Costs are paid with the coming week. */
function canStart(h,kind){return kind==='licence'?h.tier===0&&!h.proj.licence:kind==='restaurant'?h.tier>=1&&!h.restaurant&&!h.proj.rest:false;}
function startProject(h,kind){if(!canStart(h,kind))return false;
  if(kind==='licence'){h.proj.licence=GROWTH.licenceWeeks;h.invest+=GROWTH.licenceCost;}
  else{h.proj.rest=GROWTH.restWeeks;h.invest+=GROWTH.restCost;}return true;}
const maxStaff=h=>TIERS[h.tier].maxStaff;
function simulateWeek(g){
  const w=g.week,c=CITIES[g.city],rng=g.rng;g.hotels.forEach(h=>{if(!h.isPlayer)botDecide(g,h);});
  const E=weekEffects(g,w);const season=seasonMult(g,w);const segDemand={};const K=marketScale(g);
  SEGMENTS.forEach(s=>{const fs=clamp(c.foreign*s.fb,0,.95);const d=c.demand[s.id]*K*season*E.seg[s.id]*((1-fs)*E.domestic+fs*E.foreign)*(0.92+rng()*0.16);segDemand[s.id]={total:d,fs};});
  g.hotels.forEach(h=>{h.stock.billboard=h.stock.billboard*CHANNELS.billboard.decay+h.mk.billboard/1000;h.stock.online=h.stock.online*CHANNELS.online.decay+h.mk.online/1000;
    let add=0;h.infCred=null;if(h.inf!=='none'){const I=INFLUENCER[h.inf];h.infCred=I.cred[0]+rng()*(I.cred[1]-I.cred[0]);add=I.cost/1000*h.infCred;}
    h.stock.influencer=h.stock.influencer*CHANNELS.influencer.decay+add;});
  const A0=A0_BASE*E.A0*K;const res={};g.hotels.forEach(h=>res[h.id]={sold:{wd:0,we:0},rev:{wd:0,we:0},otaRev:0,seg:{},aw:{}});
  g.hotels.forEach(h=>SEGMENTS.forEach(s=>res[h.id].aw[s.id]=awareness(h,s).aw));
  ['wd','we'].forEach(p=>{const want={},segBook={};g.hotels.forEach(h=>want[h.id]=0);
    SEGMENTS.forEach(s=>{const D=segDemand[s.id].total*(p==='wd'?s.wdShare:1-s.wdShare);const A={};let sum=0;const wtp=s.wtp*E.wtp;
      g.hotels.forEach(h=>{const a=awareness(h,s);const U=s.bp*(1-h.price[p]/wtp)+0.9*(h.R-3.5);A[h.id]={v:a.aw*Math.exp(U)*Math.pow(h.rooms/8,GROWTH.sizePow),ota:a.otaShare};sum+=A[h.id].v;});
      g.hotels.forEach(h=>{const b=D*A[h.id].v/(A0+sum);segBook[h.id+s.id]={b,ota:A[h.id].ota};want[h.id]+=b;});});
    const cap={},filled={};let spill=0;
    g.hotels.forEach(h=>{cap[h.id]=(h.rooms-h.closed)*NIGHTS[p];filled[h.id]=Math.min(cap[h.id],want[h.id]);spill+=Math.max(0,want[h.id]-cap[h.id])*.5;});
    if(spill>0){const room=g.hotels.filter(h=>filled[h.id]<cap[h.id]);let tw=0;room.forEach(h=>tw+=want[h.id]+.01);room.forEach(h=>{filled[h.id]=Math.min(cap[h.id],filled[h.id]+spill*(want[h.id]+.01)/tw);});}
    g.hotels.forEach(h=>{const scale=want[h.id]>0?filled[h.id]/want[h.id]:0;const sold=Math.round(filled[h.id]);res[h.id].sold[p]=sold;res[h.id].rev[p]=sold*h.price[p];
      SEGMENTS.forEach(s=>{const sb=segBook[h.id+s.id];const n=sb.b*scale;res[h.id].seg[s.id]=(res[h.id].seg[s.id]||0)+n;res[h.id].otaRev+=n*h.price[p]*sb.ota;});});});
  const out={week:w+1,info:weekInfo(g,w),season,tl:g.timeline[w],E,hotels:{},news:[]};
  const avgPrice=h=>(h.price.wd*5+h.price.we*2)/7;
  const others=g.hotels.filter(h=>!h.isPlayer);const compAvgPrice=others.reduce((a,h)=>a+avgPrice(h),0)/others.length;
  // Classroom: each hotel is compared with every other hotel in the market (single player keeps the bots' average).
  const compAvgFor=g.multi?(h=>{const o=g.hotels.filter(x=>x!==h);return o.reduce((a,x)=>a+avgPrice(x),0)/o.length;}):(()=>compAvgPrice);
  const eventWeek=g.timeline[w].scheduled.some(e=>!e.cancelled);
  g.hotels.forEach(h=>{
    const r=res[h.id];const sold=r.sold.wd+r.sold.we;const occRooms=sold/7;const avgP=(r.rev.wd+r.rev.we)/(sold||1);
    const segQ={};let qS=0,eS=0,rS=0,nS=0,adequacy=0,lang=0;
    const fbOn=h.restaurant&&h.staff.some(x=>x.role==='fb');SEGMENTS.forEach(s=>{const t=teamQuality(h,s,segDemand[s.id].fs,sold);if(fbOn)t.q+=FNB.qBoost*FNB.capture[s.id]/.5;adequacy=t.adequacy;lang=t.lang;const Ex=30+30*Math.min(avgP/s.wtp,1.6);const rating=clamp(3.4+(t.q-Ex)/12,1,5);
      segQ[s.id]={q:t.q,e:Ex,rating,n:r.seg[s.id]||0};const n=r.seg[s.id]||0;if(n>0){qS+=t.q*n;eS+=Ex*n;rS+=rating*n;nS+=n;}});
    const Q=nS?qS/nS:0,Ex=nS?eS/nS:0;let rating=nS?rS/nS:0;const notes=[];const crises=[];
    // internal crises (Faulkner: self-inflicted crisis)
    const last=h.history[h.history.length-1];
    let pPR=.02+(last&&last.rating&&last.rating<3?.08:0)+(adequacy<.8&&sold>0?.04:0);
    if(rng()<pPR){const v=Math.floor(rng()*4);crises.push({id:'pr',v});h.R=Math.max(1,h.R-.45);}
    let extra=0;
    if(last&&last.occ>.92&&rng()<.15){crises.push({id:'overbook'});extra+=COST.overbook;h.R=Math.max(1,h.R-.2);}
    if(h.closedWeeks>0){h.closedWeeks--;if(h.closedWeeks===0)h.closed=0;}
    else if(rng()<.03){crises.push({id:'repair'});extra+=COST.repair;h.closed=2;h.closedWeeks=2;}
    const myP=(h.price.wd*5+h.price.we*2)/7;
    if(eventWeek&&myP>compAvgFor(h)*1.6&&rng()<.3){crises.push({id:'gouging'});h.R=Math.max(1,h.R-.25);}
    const newRev=Math.round(sold*.15);if(newRev>0){h.R=(h.R*h.N+rating*newRev)/(h.N+newRev);h.N+=newRev;}
    if(h.infCred!==null&&rating&&rating<3){h.R=Math.max(1,h.R-.25);notes.push('infBad');}
    let fine=0,fakeCost=0,caught=false;
    if(h.fake){fakeCost=COST.fake;h.R=(h.R*h.N+5*6)/(h.N+6);h.N+=6;if(rng()<.25){caught=true;h.R=Math.max(1,h.R-.7);fine=COST.fine;h.otaBan=3;h.fakeCaught++;notes.push('caught');}}
    else if(h.otaBan>0)h.otaBan--;
    const nFO=h.staff.filter(s=>s.role==='fo').length,nHK=h.staff.filter(s=>s.role==='hk').length;
    // Room-nights each person handled: front office also cleans when there is no housekeeper.
    const loadFO=nFO?(nHK?sold:2*sold)/nFO:0,loadHK=nHK?sold/nHK:0;const nFB=h.staff.filter(s=>s.role==='fb').length;
    // F&B workload uses last week's diners, scaled so FNB.cap diners per person = the 30 room-night cap.
    const loadFB=h.restaurant&&nFB?(h.lastCovers||0)/nFB*ROLES.fb.cap/FNB.cap:0;
    const loadOf=s=>s.role==='fo'?loadFO:s.role==='hk'?loadHK:s.role==='fb'?loadFB:0;
    const load=h.staff.length?sold/h.staff.length:0;const bonusPer=h.staff.length?h.bonus/h.staff.length:0;
    h.staff.forEach(s=>{s.sat=clamp(s.sat+2-Math.max(0,loadOf(s)-ROLES[s.role].cap)*LOAD_HIT+bonusPer/100-E.staffHit,0,100);});
    const teamSat=h.staff.length?h.staff.reduce((a,s)=>a+s.sat,0)/h.staff.length:0;const quits=[];
    if(h.staff.length&&teamSat<40){h.staff=h.staff.filter(s=>{if(rng()<.15){quits.push(s.name||s.id);return false;}return true;});}
    const team={};['app','serv','exp','prof','lang'].forEach(k=>team[k]=h.staff.length?h.staff.reduce((a,s)=>a+s[k],0)/h.staff.length:0);
    const fnb=restaurantWeek(g,h,r,season,E,sold);
    const revenue=r.rev.wd+r.rev.we,commission=r.otaRev*OTA_COMMISSION,infCost=h.inf!=='none'?INFLUENCER[h.inf].cost:0;
    const costs={severance:h.severance||0,fixed:(COST.fixed+(h.rooms-8)*GROWTH.fixedPerExtraRoom+(h.restaurant?GROWTH.restFixed:0))*E.cost,invest:h.invest||0,food:fnb.foodCost,variable:COST.perRoomNight*sold,salaries:h.staff.reduce((a,s)=>a+s.salary,0),bonus:h.bonus,marketing:h.mk.billboard+h.mk.online+infCost,commission,fake:fakeCost,fine,crisis:extra,interest:h.cash<0?-h.cash*COST.interest:0};
    h.severance=0;h.invest=0;const costTotal=Object.values(costs).reduce((a,b)=>a+b,0);const profit=revenue+fnb.revenue-costTotal;h.cash+=profit;h.profitCum+=profit;
    // eWOM: review distribution
    const dist=[0,0,0,0,0];for(let i=0;i<newRev;i++){const v=clamp(Math.round(rating+(rng()+rng()+rng()-1.5)*1.1),1,5);dist[v-1]++;}
    let awAvg=0;SEGMENTS.forEach(s=>awAvg+=r.aw[s.id]/4);
    const rec={sold,soldP:r.sold,occ:sold/(h.rooms*7),occP:{wd:r.sold.wd/(h.rooms*5),we:r.sold.we/(h.rooms*2)},revenue,adr:sold?revenue/sold:0,revpar:revenue/(h.rooms*7),rooms:h.rooms,tier:h.tier,fnb,
      price:Object.assign({},h.price),Q,E:Ex,rating,R:h.R,N:h.N,teamSat,team,load,loadFO,loadHK,loadFB,roles:{fo:nFO,hk:nHK,fb:nFB},adequacy,lang,quits,costs,costTotal,profit,cash:h.cash,awAvg,aw:r.aw,segQ,dist,newRev,
      commission,otaRev:r.otaRev,caught,notes,crises,inf:h.inf,infCred:h.infCred,fake:h.fake,otaBan:h.otaBan,seg:r.seg,staffN:h.staff.length,closed:h.closed};
    h.history.push(rec);out.hotels[h.id]=rec;h.inf='none';advanceProjects(h);
    if(!h.isPlayer)crises.forEach(cr=>out.news.push(Object.assign({hotel:h.id},cr)));
  });
  // Competitive set and indices (STR style). Single player: the 3 bots vs 'you'. Classroom: every other hotel, per player.
  const compOf=list=>{const cSold=list.reduce((a,b)=>a+b.sold,0),cRev=list.reduce((a,b)=>a+b.revenue,0),cAvail=list.reduce((a,b)=>a+b.rooms*7,0);
    const comp={occ:cSold/cAvail,adr:cSold?cRev/cSold:0,revpar:cRev/cAvail,aw:{},R:list.reduce((a,b)=>a+b.R,0)/list.length,Q:list.reduce((a,b)=>a+b.Q,0)/list.length};
    SEGMENTS.forEach(s=>comp.aw[s.id]=list.reduce((a,b)=>a+b.aw[s.id],0)/list.length);return comp;};
  const idxOf=(y,c)=>({mpi:c.occ?y.occ/c.occ*100:0,ari:c.adr&&y.adr?y.adr/c.adr*100:0,rgi:c.revpar?y.revpar/c.revpar*100:0});
  if(g.multi){out.compBy={};out.idxBy={};g.hotels.filter(h=>h.isPlayer).forEach(h=>{const c=compOf(g.hotels.filter(x=>x!==h).map(x=>out.hotels[x.id]));out.compBy[h.id]=c;out.idxBy[h.id]=idxOf(out.hotels[h.id],c);});}
  else{out.comp=compOf(g.hotels.filter(h=>!h.isPlayer).map(h=>out.hotels[h.id]));out.idx=idxOf(out.hotels.you,out.comp);}
  out.marketOcc=g.hotels.reduce((a,h)=>a+out.hotels[h.id].sold,0)/g.hotels.reduce((a,h)=>a+h.rooms*7,0);
  g.news.push(...out.news.map(n=>Object.assign({week:w+1},n)));
  g.week++;return out;}
function finalScores(g){
  const maxPos=Math.max(0,...g.hotels.map(h=>h.profitCum));
  return g.hotels.map(h=>{const fin=h.profitCum<=0||maxPos===0?0:h.profitCum/maxPos*100;const rep=(h.R-1)/4*100;
    const sats=h.history.map(x=>x.teamSat);const staff=sats.length?sats.reduce((a,b)=>a+b,0)/sats.length:0;
    return {id:h.id,name:h.name,fin,rep,staff,score:SCORE_W.fin*fin+SCORE_W.rep*rep+SCORE_W.staff*staff,profit:h.profitCum,cash:h.cash,R:h.R};}).sort((a,b)=>((b.profit>0)-(a.profit>0))||(b.score-a.score));}

export {MARKET_UNIT, marketScale, TIERS, GROWTH, FNB, startProject, canStart, maxStaff, MAX_STAFF, ROLES, HK_COVER, LOAD_HIT, CAND_ROLES, LANG_RANGE, teamQuality, newGame, simulateWeek, finalScores, seasonMult, seasonLabel, weekInfo, tmdSeason, buildTimeline, weekEffects, refPrice, salaryOf, mulberry32, hashSeed, clamp, ROOMS, NIGHTS, WEEKS, SEGMENTS, MAPS, CITIES, NATIONAL, SEEDED, CANCEL_P, SHOCKS, INTERNAL, CHAOS, CHANNELS, INFLUENCER, OTA_BOOST, OTA_COMMISSION, COST, START_CASH, SCORE_W, ARCH, SKILL};
