/* Reference links shown in the game (see docs/sources.md). */
export const SRC = {
  str: 'https://str.com/resourcesglossary/revpar-indexrevenue-generating-index-rgi',
  ehl: 'https://insights.ehl.edu/hotel-industry-performance',
  ehl2: 'https://insights.ehl.edu/what-is-revpar',
  chekin: 'https://chekin.com/en/blog/str-report-for-hotels/',
  rpgRev: 'https://roompricegenie.com/revenue-per-available-room-revpar',
  rpgAdr: 'https://roompricegenie.com/glossary/average-daily-rate-adr',
  axis: 'https://blog.axisrooms.com/revenue-management-glossary/',
  akia: 'https://www.akia.com/glossary/r',
  raft: 'https://www.raftlabs.com/tools/revpar-calculator',
  crookall: 'https://ideas.repec.org/a/sae/simgam/v41y2010i6p898-920.html',
  ftc: 'https://www.ftc.gov/news-events/news/press-releases/2024/08/federal-trade-commission-announces-final-rule-banning-fake-reviews-testimonials',
  nso: 'https://www.nso.go.th/nsoweb/downloadFile/stat_main_nso/FgpN/file_th',
  servqual: 'https://en.wikipedia.org/wiki/SERVQUAL',
  tmd: 'https://www.nso.go.th/public/e-book/Statistical-Yearbook/SYB-2023/621/',
  phuket: 'https://www.phuketferry.com/th/the-weather-and-climate-of-phuket.html',
  phuket2: 'https://www.nomadotravel.app/th/guides/best-time-to-visit-phuket',
  ranong: 'https://www.silpa-mag.com/history/article_159902',
  festival: 'https://www.byklo.rent/th/blog/when-to-visit-phuket-weather/',
  litvin: 'https://pure.psu.edu/en/publications/electronic-word-of-mouth-in-hospitality-and-tourism-management/',
  faulkner: 'https://1library.net/article/key-terms-discussion-assessment-literature.yexrev0q',
  faulknerPhases: 'https://dspace.angliss.edu.au/handle/20.500.12270/350',
  ne: 'https://github.com/nvkelso/natural-earth-vector',
};
