// Copy the pure game modules into the Supabase function folder (the function bundle cannot import from src/).
// Run after changing src/sim/*.js: npm run sync:server. tests/server-sync.test.mjs fails if the copies are stale.
import fs from 'node:fs';

export const SHARED = ['core.js', 'save.js', 'classroom.js', 'analysis.js'];
const from = new URL('../src/sim/', import.meta.url), to = new URL('../supabase/functions/_shared/', import.meta.url);
const header = '// GENERATED by scripts/sync-server.mjs from src/sim/ — do not edit here.\n';

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  fs.mkdirSync(to, { recursive: true });
  for (const f of SHARED) fs.writeFileSync(new URL(f, to), header + fs.readFileSync(new URL(f, from), 'utf8'));
  console.log(`copied ${SHARED.join(', ')} -> supabase/functions/_shared/`);
}
